In [1]:
import numpy as np 
from sklearn import datasets,metrics 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  

In [2]:
iris=datasets.load_iris() 
X=iris.data 
y=iris.target 

In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) 

In [4]:
nb_classifier=GaussianNB() 

In [5]:
nb_classifier.fit(X_train,y_train) 

GaussianNB()

In [6]:
y_pred=nb_classifier.predict(X_test) 

In [7]:
res=confusion_matrix(y_test,y_pred) 

In [8]:
print("confusion_matrix \n",res) 

confusion_matrix 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [9]:
res1=classification_report(y_test,y_pred) 

In [10]:
print("Classification_report \n",res1) 

Classification_report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [11]:
accuracy=accuracy_score(y_test,y_pred) 
print("Accuracy:\n",accuracy) 

Accuracy:
 1.0
